services:
  postgres:
    image: postgres:16-alpine  # Dùng bản Alpine cho nhẹ
    container_name: crypto-postgres
    restart: always
    environment:
      - POSTGRES_USER=admin         # Username truy cập DB
      - POSTGRES_PASSWORD=admin123  # Password (nhớ đổi khi deploy thật)
      - POSTGRES_DB=crypto_portfolio_db # Tên Database sẽ tự tạo
    ports:
      - "5433:5432" # Map cổng 5432 của container ra máy thật
    volumes:
      - postgres_data:/var/lib/postgresql/data # Quan trọng: Lưu dữ liệu ra ngoài container

volumes:
  postgres_data: # Định nghĩa volume để dữ liệu không mất khi tắt Docker